export const AWS_CONSTANT = {
  S3_EXPIRES_UPLOAD: 600,
  PRESIGN_UPLOAD: {
    DEFAULT_S3_UPLOAD_FILE_MIN: 10,
    DEFAULT_S3_UPLOAD_FILE_MAX: 10 * 1024 * 1024,
    DEFAULT_S3_UPLOAD_FILE_ACL: "bucket-owner-full-control",
  },
};
